apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quartz

resources:
  - namespace.yaml
  - technical-agent.yaml
  - trading-agent.yaml
  - portfolio-manager.yaml

